const reporter = require('multiple-cucumber-html-reporter');
const path = require('path');
const fs = require('fs');

const reportDir = path.join(__dirname, 'reports');

reporter.generate({
  jsonDir: reportDir,
  reportPath: path.join(reportDir, 'multiple-html'),
  reportName: 'Proxy Service Test Report',
  pageTitle: 'Proxy Service - Cucumber Report',
  metadata: {
    browser: {
      name: 'playwright-api',
      version: 'n/a',
    },
    device: 'Local machine',
    platform: {
      name: process.platform,
      version: process.version,
    },
  },
  customData: {
    title: 'Run Info',
    data: [
      { label: 'Project', value: 'Simple Proxy Service' },
      { label: 'Generated on', value: new Date().toISOString() },
    ],
  },
});
const htmlPath = path.join(reportDir, 'multiple-html', 'index.html');

try {
  if (fs.existsSync(htmlPath)) {
    let html = fs.readFileSync(htmlPath, 'utf8');
    const originalFooter = `            <div class="created-by">\n                <p>Maintained by Wasiq Bhamla. Find me on:</p>\n                <a href="https://www.youtube.com/@WasiqBhamla" target="_blank"><i class="fa fa-youtube-square fa-2x"></i></a>\n                <a href="https://github.com/WasiqB/" target="_blank"><i class="fa fa-github-square fa-2x"></i></a>\n                <a href="https://www.linkedin.com/in/wasiqbhamla/" target="_blank"><i class="fa fa-linkedin-square fa-2x"></i></a>\n                <a href="https://stackoverflow.com/users/5320558/wasiq-bhamla" target="_blank"><i class="fa fa-stack-overflow fa-2x"></i></a>\n            </div>`;

    const customFooter = `            <div class="created-by">\n                <p>Generated by Wafa Karima Rahmani. Find me on:</p>\n                <a href="https://github.com/wafa-rahmani" target="_blank"><i class="fa fa-github-square fa-2x"></i></a>\n                <a href="https://www.linkedin.com/in/wafa-karima-rahmani/" target="_blank"><i class="fa fa-linkedin-square fa-2x"></i></a>\n            </div>`;

    html = html.replace(originalFooter, customFooter);
    fs.writeFileSync(htmlPath, html, 'utf8');
  }
} catch (err) {
  console.error('Failed to post-process HTML report footer:', err);
}

console.log('Multiple Cucumber HTML Report generated at:', path.join(reportDir, 'multiple-html'));
