const reporter = require('multiple-cucumber-html-reporter');
const path = require('path');
const fs = require('fs');

const reportDir = path.join(__dirname, '..', 'reports');

reporter.generate({
  jsonDir: reportDir,
  reportPath: path.join(reportDir, 'multiple-html'),
  reportName: 'Proxy Service Test Report',
  pageTitle: 'Proxy Service - Cucumber Report',
  metadata: {
    browser: {
      name: 'playwright-api',
      version: 'n/a',
    },
    device: 'Local machine',
    platform: {
      name: process.platform,
      version: process.version,
    },
  },
  customData: {
    title: 'Run Info',
    data: [
      { label: 'Project', value: 'Simple Proxy Service' },
      { label: 'Generated on', value: new Date().toISOString() },
    ],
  },
});
// Post-process all generated HTML files (overview + feature pages) to replace
// the default maintainer footer with your name and social links.
const reportRoot = path.join(reportDir, 'multiple-html');

const footerCustom = `        <div class="created-by">\n            <p>Generated by Wafa Karima Rahmani. Find me on:</p>\n            <a href="https://github.com/wafa-rahmani" target="_blank"><i class="fa fa-github-square fa-2x"></i></a>\n            <a href="https://www.linkedin.com/in/wafa-karima-rahmani/" target="_blank"><i class="fa fa-linkedin-square fa-2x"></i></a>\n        </div>`;

function updateFooterInFile(filePath) {
  try {
    if (!fs.existsSync(filePath)) return;
    let html = fs.readFileSync(filePath, 'utf8');
    const marker = 'Maintained by Wasiq Bhamla';
    if (!html.includes(marker)) return;

    const divStart = html.lastIndexOf('<div class="created-by">');
    const divEnd = html.indexOf('</div>', divStart);
    if (divStart === -1 || divEnd === -1) return;

    const originalBlock = html.slice(divStart, divEnd + '</div>'.length);
    html = html.replace(originalBlock, footerCustom);
    fs.writeFileSync(filePath, html, 'utf8');
  } catch (err) {
    // eslint-disable-next-line no-console
    console.error('Failed to post-process HTML report footer for', filePath, err);
  }
}

// Update main index page
updateFooterInFile(path.join(reportRoot, 'index.html'));

// Update all feature overview/detail pages
const featuresDir = path.join(reportRoot, 'features');
if (fs.existsSync(featuresDir)) {
  for (const file of fs.readdirSync(featuresDir)) {
    if (file.endsWith('.html')) {
      updateFooterInFile(path.join(featuresDir, file));
    }
  }
}

console.log('Multiple Cucumber HTML Report generated at:', reportRoot);
